title: Welcome
author: Suzanna Semaan

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

user_url: "https://www.linkedin.com/in/suzanna-s-" }
